### ND-Research Build Matrix ###
language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
osx_image:
  - xcode11.2
  - xcode10.1
dist: bionic
arch:
  - arm64
  - amd64

notifications:
  email: false


### Installation Procedure ###
script:
  - mkdir build && cd build
  - cmake ../. -Dnd-research_build_tests=ON
  - make && sudo make install
  - cd OpenMD/test
  - ctest
