### ND-Research Build Matrix ###
language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
osx_image:
  - xcode11.2
  - xcode10.1
dist: bionic
arch:
  - arm64
  - amd64

notifications:
  email: false


### Standard Installation Procedure ###
script:
  - mkdir build && cd build
  - cmake ../. -Dnd-research_build_tests=ON
  - make && sudo make install
  - cd nd-research/test
  - ctest --output-on-failure


### Provide Code Coverage Reports ###
matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      arch: amd64
      addons:
        apt:
          packages:
            - python-pip
            - lcov
          update: true
      install:
        - if [ $TRAVIS_OS_NAME = linux ]; then pip install --user cpp-coveralls; fi
      script:
        - mkdir build && cd build
        - cmake ../. -Dnd-research_coverage=ON
        - make && sudo make install
        - cd nd-research/test
        - ctest --output-on-failure
        - lcov --directory . --capture --output-file coverage.info
        - lcov --remove coverage.info '*gtest*' '*utils-api*' '*cpp-units*' '*/test/*' '/usr/*' --output-file coverage.info
        - coveralls -r ../../../. -l coverage.info -n
